### PR TITLE
Added JAE LY Angled connectors

### PR DESCRIPTION
**Pull request by SchrodingersGat**
This PR adds the complete series of LY angled connectors

**Datasheet**
http://www.jae.com/z-en/pdf_download_exec.cfm?param=SJ038187.pdf

### CODE REVIEW

**Comment by pointhi** [comment]
Please check `Dimension B`. If you are interested about a real top view, you also have to consider `Dimesion C`.

the rest looks fine

**Comment by SchrodingersGat** [comment]
Can you provide a bit more info as to what you mean here? :) Happy to adjust but not quite sure where the issue is...

**Comment by evanshultz** [comment]
@pointhi Can you share more about what you found so we can complete this PR? Thanks!

**Comment by SchrodingersGat** [comment]
KLC issues have been addressed

**Comment by evanshultz** [comment]
@pointhi @poeschlr @jkriege2 Is someone able to review this?

**Comment by poeschlr** [comment]
Am i right in assuming these footprints are script generated? (Makes checking easier.)

The pin order might not be the best choice for the symbols we currently have. (odd/even would be better such that we can use the current symbols.)
In the datasheet pin names are given similar to BGA pin numbers but with letter and number exchanged (1A, 2A, .... nA; 1B, 2B, ..., nB) See issue for a discussion if we should create such symbols https://github.com/KiCad/kicad-library/issues/1451

Pin 1 marker on fab layer is missing.

I assume @pointhi meant the following with his mention of dimension b and c (I don't think this is important/ we can merge without changes to it.):
screenshot from 2017-07-26 23-48-15

**Comment by evanshultz** [comment]
@SchrodingersGat Can you review Rene's comments above, please?

**Pull request closed without merging**
