### PR TITLE
Create FF0881SA1.kicad_mod

### PR DESCRIPTION
**Pull request by savenlid**
Created best effort to datasheet
http://www.jae.com/z-en/pdf_download_exec.cfm?param=SJ108178.pdf

not field proven yet.

### CODE REVIEW

**Comment by pointhi** [comment]
Please fix KLC:

```
Violating Rule 10.2
    Doc property contains a full description of footprint.
  Violating Rule 10.5
    Attributes is set to the appropriate value, see tooltip for more information.
  Violating Rule 10.6
    All other properties are left to default values. (Move and Place: Free; Auto Place: 0 and 0,  Local
    Clearance Values: 0)
  Violating Rule 6.6
    Courtyard line has a width 0.05mm. This line is placed so that its clearance is measured from its
    center to the edges of pads and body, and its position is rounded on a grid of 0.05mm.
```

Also:
- reference and value text shouldn't overlap. I would suggest you to put the value field to the bottom

I would suggest you to use https://github.com/KiCad/kicad-library-utils to find most KLC errors, and the look for other stuff which could be wrong or described in another way in the [KLC](https://github.com/KiCad/kicad-library/blob/master/KiCad_Library_Convention.txt)

**Comment by evanshultz** [comment]
@savenlid Will you be able to review the comments above and finish this PR soon?

**Comment by savenlid** [comment]
KLC rule 10.4.i

only wrl files allowed

thats crazy

change that to only step files allowed

no component manufacturer supplies wrl files and no-body wants them anyway

or maybe someone in oklahoma does, but i wouldn't know

anyway to force wrl only in KLC is not good

IMHO
/NIcholas


2017-06-22 11:19 GMT+02:00 Rene Pöschl <notifications@github.com>:

**Comment by poeschlr** [comment]
Kicad stable can not work with step.

You are free to use step in your personal libs. But the official library needs to take care of the people who use the stable version.

The current nightly build can support step. (Even if the path ends in .wrl it can use step files)
The same holds true for kicad stepup it just "ignores" the file ending in the footprint settings.
But again, kicad stable does not.

**Comment by savenlid** [comment]
ok

but solder mask clearance is up to the footprint to decide, not
upper-layers design rules nor KLC

only the footprint can be the footprint
its the job of the footprint to be the footprint
one of its responsibilities is to define solder mask as well as solder
paste,
to decide to the footprints liking.

soon we will also be given free-shapes for that, pads, paste, mask.

for example look at 0201 where solder-paste do not follow pad shape

and same goes for solder mask, can be free shape and not closely related to
pad,
up to footprint.

or did i misunderstand KLC 10.3.iii ?




2017-06-22 12:29 GMT+02:00 Rene Pöschl <notifications@github.com>:

**Comment by poeschlr** [comment]
> but solder mask clearance is up to the footprint to decide, not upper-layers design rules nor KLC 

This depends. In most cases the rules of the fab define what can be used.
I would say if there is no special reason to define it at the footprint (or even pad) level, then it should be defined at the project level. This way a footprint can be used for manufacturing at a cheap fab that requires large clearances as well as a very expensive fab that can live with very small clearances.

**Comment by savenlid** [comment]
if fab cant do it they will adjust with pre-processing tools, which is part
of their daily life and process.

Its same to say in an analogy that we should be able to resize all trace
widths with an upper laye knob in the tools just to pamper manufacturers.

it doesn't work that way, they pamper themselves in their own
pre-processing.
as they also do for the silkscreen you accidentally put on some pads.


The absolute power of what should be nominal for the footprint should be in
the footprint, only the footprint knows the part requirements.
They are not generic.
also soon they hopefully will be free-form, as of now can only follow pads,
and that sometimes as very bad idea.
once free-form no one can make assumptions between mask and pad, or solder
and pad.


no reason ever to adjust manufacturing output files to adjust to fab

they will adjust themselves to their capabilities.

it may have sounded like a good idea, but its just plain wrong nonetheless.



2017-06-22 13:14 GMT+02:00 Rene Pöschl <notifications@github.com>:

**Comment by poeschlr** [comment]
With if there is a reason, i meant:
If it is given in either the manufacturers datasheet or in an application node for the part in question, AND the footprint is specific to one component then the clearance settings may be defined either in the footprint or pad settings. (pad settings if different mask settings are required for different pads, otherwise footprint settings.)
A good example for such a pull request where we accepted a footprint defined clearance can be found here: https://github.com/KiCad/Housings_BGA.pretty/pull/12

Which means for you:
If you can give a document that shows that this footprint should have a specific setting, the klc rule can be ignored.
Just state in the pull request description where we maintainers can find this information in the linked document. Yes travis might complain. But as long as you can give a reason why for this specific footprint this rule does not apply we will accept the footprint.

**Comment by evanshultz** [comment]
@savenlid In addition to the topic above, there are a number of other KLC violations. We greatly value all contributions that can be added to the library and I'd like to incorporate your work if possible. On the other hand, if KLC is wrong/poor then we're open to reviewing and changing it (just see above), so please share your feedback in a constructive way or update this footprint if you're willing. Thank you!

**Comment by savenlid** [comment]
O looked on the KLC violations and could see nothing but minor/unclear
differences

iolating Rule 10.2
    Doc property contains a full description of footprint.
  Violating Rule 10.5
    Attributes is set to the appropriate value, see tooltip for more
information.
  Violating Rule 10.6
    All other properties are left to default values. (Move and Place:
Free; Auto Place: 0 and 0,  Local
    Clearance Values: 0)
  Violating Rule 6.6
    Courtyard line has a width 0.05mm. This line is placed so that its
clearance is measured from its
    center to the edges of pads and body, and its position is rounded
on a grid of 0.05mm.

Not sure what Rule 10.2 tries to say to me, angry beacuse it does
contain a full description or beacuse a lack of full desription ?
I put in the datasheets definition there now.

rule 10.5, dont know what attribute is refered to

10.6 , yes i like 0.05 solder mask keep-out, but i did now put it down to 0

6.6 i did align court yard to 0.05mm grid

This footprint is running in production and is working fine

Attached here is also now with 3D step file associated.





2017-06-23 3:21 GMT+02:00 evanshultz <notifications@github.com>:

**Comment by evanshultz** [comment]
@savenlid There is no commit above. Please push you patch for review.

While KLC isn't perfect, and never will be, it is the standard that parts must meet to be merged. To keep the library standardized all submissions must follow KLC (unless specific deviations are accepted). If there is some part of KLC that is wrong or could be improved, then please bring it up constructively. Thanks!

**Comment by savenlid** [comment]
10.4, its a rule with such strange requirements for unclear reasons
If name needs to be the same, it cannot be used in other footprints ?
Ok thats fine I guess, I can copy it.
But the directory structure ?, I am not sure how I should interpret this.
I did change the file name to same as footprint, but it is a step and not wrl,
I will not rename a step into a wrl, because its not a wrl file.

7.3.i   I would never be able to use silkscreen if always needs to be 1x1mm  I would have to remove almost all silk, it will just not fit, i use 0.5x0.5x0.1 as standard when and even then not always able to fit it.
I could remove it alltogheter that would be easier for than bring it up to 1x1

7.4 breaks also but I dont know if its i , ii or iii
KLC could be more clear on the sub-sections, because I am lost here.


I think you should create a parallel structure/mechanism where non KLC footprint can live
They are useful even if non KLC.
People can use them as is, or modify, as it is now my footprints will be thrown away for the public eye.
More importantly I think is to know if a footprint has been trough production or not.
And if that was volume production.

**Comment by poeschlr** [comment]
Your first remark about rule 10.4:
have a look at 10.4.ii: Variations of the same footprint can use the same 3d shape. Yes the travis script will give a warning here but how should a computer know that a footprint is just a variation of another footprint.

About the wrl files. If you want to use the kicad internal 3d viewer you need a wrl file. This can be created with freecad and the kicad stepup scripts. Have a look at our [new packages 3d](https://github.com/KiCad/packages3D) repo and its wiki/readme for more details about that.

You are not supplying this footprint (only) for your own personal use. You supply it to the official lib. For that reason it needs to be made in such a way that it can be used in kicad stable. Again: KiCad stable does not support step. The 3d file path in the footprint settings has to end in .wrl. It also has to start with ${KISYS3DMOD}/. 
This does not mean you have to supply a wrl file. It does not mean that you are not allowed to use step for your own personal use.
This rule is final. (Maybe when kicad 5 comes out and kicad has native support for step we can talk again. But for backwards compatibility reasons we might still vote for having the file name end in .wrl)

Kicad nightly does support step. It does ignore the file ending (in the footprints 3d settings) as does kicad stepup. Both of them expect the step file to be in the same folder with the same file name as the wrl file. So please give the path in the footprint settings the file ending .wrl

**Comment by evanshultz** [comment]
@savenlid Have you made any updates? If so, please push the changes for review. This may make it easier to provide guidance for this specific footprint.

If you would take a bit of time to review other footprints in the library, hopefully which are KLC-compliant, I think it would be much easier to understand these requirements. There are a number of `Connectors_` libraries which have a multitude of footprints which would be a decent example.

First, the footprint name is wrong. It should be something like `JAE_FF08-81P-81x0.4mm_Angled`. It would be nice if somebody else could comment on this since JAE calls it a 0.2mm pitch but the footprint itself appears to have a pin pitch of 0.4mm. @poeschlr?

10.4: Only WRL files are linked to the footprint at this time, and even if the 3D model does not exist the footprint should include the reference to the 3D model so it's easy to add the 3D model later. You will add the following to the bottom of your footprint (and correct the footprint name too):
```
(model ${KISYS3DMOD}/Connectors_JAE.3dshapes/FF0881SA1.wrl
    (at (xyz 0 -0.05 0.05))
    (scale (xyz 0.39 0.39 0.39))
    (rotate (xyz -90 0 -180))
  )
```

7.3.i: 1x1mm will fit in this footprint and is what has been decided for the KiCad library.

7.4: What is the specific question here. There are a number of sub-sections, but each one has a purpose and the example picture in KLC and existing footprints in the KiCad library will be illustrative.

In sum, KLC are the rules that footprints must adhere to in order to be in the library. You are free to have your own opinion or set your own rules, but to be merged into the KiCad library all submissions need to be KLC-compliant.

**Comment by evanshultz** [comment]
Thanks, @poeschlr, for taking some time to jump in.

**Comment by evanshultz** [comment]
Here is an image of the current footprint (from the first post):
image

Initial review:
- Correct footprint name as mentioned above (6).
- Add 3D model info (10.4).
- Ref des is fine above, but footprint name should be below.
- Ref des also needs to be on the F.Fab layer (7.4.iii).
- Silk should follow the fab layer shape, but outside so that it is visible after assembly (7.3.iv).
- Silk line width is 0.12mm (7.3.v).
- Courtyard should be 0.5mm from the part body on a 0.1mm grid (7.5.iii, 7.5.iv.c). Edit by poeschlr: or 0.5mm outside of pads whatever is larger in the particular direction. (For this footprint: towards the top: 0.5mm outside the pads, all other directions: 0.5mm outside the body.)
- Pin 1 mark can be different styles. For this connector, a small triangle may be best; see `Connectors_Samtec:LSHM-140-xxx-x-DV-A-N` for an example (7.3.vi-7.3.viii).

And if all this gets addressed and this footprint is merged, it would be nice to have the other parts in the family (pin counts of 25, 29, 41, 51, and 71) for completeness.

**Comment by savenlid** [comment]
It's because the Flex connector is 0.2mm

Ofcourse

The connector resides in the JAE directory, why prefix and postfix the
partno?

Professionals know what part they need, don't pick connectors on random.

Besides, description should not be part of the file name.

Have a look at other ecad software libraries.

Cadence / Orcad
Mentor / Pads
Altium.

If you browse randomly for a connector you would browse on description /
pin count etc attributes.


This specific connector goes to a tiny led screen full HD from Sony.

If you use that led screen, you need this part no.


Den 27 juni 2017 18:25 skrev "evanshultz" <notifications@github.com>:

**Comment by evanshultz** [comment]
@savenlid If you're not willing to meet the requirements of KLC, which is required to merge this part, please say so and we can end the conversation on this and potentially a number of other PRs of yours.

**Comment by savenlid** [comment]
Yes we will need to end it.

Attributes as component type (connector, capacitor etc.
Number of poles.
Straight / angle / edge
Etc etc
Should be embedded into the part.
There should be radio boxes etc to indicate this in an organized way into
the footprint / symbol itself.

Then you can search and filter with the library manager.

Not by putting a novel into the filename.

IMHO.

If will close my PR's

Let's hope future releases or Kicad will Adress this and get us out of the
filename as description swamp.

Thanks


Den 27 juni 2017 22:17 skrev "evanshultz" <notifications@github.com>:

**Comment by evanshultz** [comment]
Sad, but OK. I'll update this footprint and create a new PR to merge it.

**Comment by savenlid** [comment]
My footprints can be found here

https://github.com/savenlid/kicad

if you find some of interest.



2017-06-28 17:20 GMT+02:00 evanshultz <notifications@github.com>:

**Pull request closed without merging**
