### PR TITLE
Add JAE FF08 series

### PR DESCRIPTION
**Pull request by evanshultz**
Fixing https://github.com/KiCad/Connectors_JAE.pretty/pull/1#issuecomment-310380008 to meet KLC.

This is the 81 pin version. Please do not merge! Once the design is settled, I'll make the other ones.

Image:
image

Questions:
- Is this footprint name OK? The pin pitch is 0.4mm, so I used that, while the FPC pitch is 0.2mm and is what JAE uses. Which is best?
- Is this the best way to indicate the latch? I used silk and fab layer lines. (Note: Since the X dimension of the latch weren't given in the datasheet I guessed as best as I could from the pad locations.)

Changes:
- Rename footprint
- Add 3D model
- Add 3D model info.
- Move footprint name should be below.
- Add ref des also needs to be on the F.Fab layer.
- Silk follows the fab layer shape.
- Change Silk line width is 0.12mm.
- Move courtyard to 0.5mm from the part body on 0.1mm grid.
- Add pin 1 mark from Connectors_Samtec:LSHM-140-xxx-x-DV-A-N.

### CODE REVIEW

**Comment by evanshultz** [comment]
I should have included the datasheet above so you didn't need to dig back into the old PR. It is at http://www.jae.com/z-en/pdf_download_exec.cfm?param=SJ108178.pdf.

**Comment by evanshultz** [comment]
Review is appreciated, but please don't merge. If all looks well, I'd like to know so then I can move on to the other parts in the family. And of course if there's a problem or suggestion I want to know as well. Thanks!

**Comment by SchrodingersGat** [comment]
I would adjust the naming slightly:

**From:** `JAE_FF08-81P-81x0.4mm_Angled`

**To:** `JAE_FF08-81P_81x0.4mm_Angled`

(i.e. the underscores separate the conceptually different parts of the filename, which is here:

* Manufacturer
* MPN
* Description
* Additional info

Thanks!

**Comment by evanshultz** [comment]
Is anyone able to give this a look? I'd like to get any feedback on changes before spinning off the other footprints in the family.

**Comment by evanshultz** [comment]
@SchrodingersGat Thanks. I didn't refresh my browser tab or get through my emails before commenting...

Any other feedback? If this is otherwise OK to go, I'll do the other parts in the family.

**Comment by SchrodingersGat** [comment]
It looks like the footprint should be rotate 90degrees CCW such that Pin-1 is top-left

**Comment by evanshultz** [comment]
Thanks. I missed that rotational change from the original footprint. In the absence of other comments, I spun off the other variants. Please review all. Thank you!

Note that it was hard to figure out the latch size/width. That is all a guess. I kept it all the same except for the 25 pin version, which I shrunk to fit within the body a similar distance as the 29 pin version. A [Google image search for "jae ff0825sa1"](https://www.google.com/search?q=jae+ff0825sa1&source=lnms&tbm=isch&sa=X&ved=0ahUKEwjZ9ZSbioDVAhUDX5QKHUPdCD4Q_AUICigB&biw=1920&bih=974) was my best piece of info.

Also, the original post above have a couple questions.

Images:
image

**Comment by evanshultz** [comment]
@SchrodingersGat @jkriege2 @poeschlr 
Does anybody have a chance to review this PR?

**Comment by evanshultz** [comment]
@SchrodingersGat You commented above. Would you be able to review this PR so it can be merged?

**Comment by SchrodingersGat** [comment]
Hi @evanshultz a few notes:

1. The 81 version still needs to be rotated correctly
1. I would rotate the F.Fab RefDes so that it matches the alignment of the connector 
1. Same rotation for the footprint name

image

Functionally the footprints look good - a few tweaks as above and I think they are ok to merge. Sorry for missing your comments above.

**Comment by evanshultz** [comment]
@SchrodingersGat Thanks for checking!

How did I miss pushing the 81 pin version after rotating it?! Sorry about that. I've also adjusted the text as you mentioned for all footprints.

**Comment by SchrodingersGat** [comment]
Thanks, that looks better :) 

One tiny thing - please increase text size of the RefDes on F.Fab to 0.15mm (0.1mm looks a bit too thin).

Thanks :)

**Comment by evanshultz** [comment]
Connectors... now with fatter text!

**Comment by SchrodingersGat** [comment]
Great work, thanks :)

**Pull request merged**
